' ******************************************************************************
' swxJRNL.swj - journal recorded on 05/31/10 by Administrateur
' *****************************************************************************
Dim swApp As Object
Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long
Dim Annotation As Object
Dim Gtol As Object
Dim DatumTag As Object
Dim FeatureData As Object
Dim Feature As Object
Dim Component As Object
Sub main()

Set swApp = Application.SldWorks

Set Part = swApp.OpenDoc4 ("D:\mémore lotfi\conception étau\nouveau étau\SUPPORT\CACHE.SLDPRT", 1, 0, "", longstatus)
Set Part = swApp.ActivateDoc ("CACHE.SLDPRT")
swApp.ActiveDoc.ActiveView.FrameWidth = 1291
swApp.ActiveDoc.ActiveView.FrameHeight = 455
swApp.ActiveDoc.ActiveView.FrameLeft = 0
swApp.ActiveDoc.ActiveView.FrameTop = 0
swApp.ActiveDoc.ActiveView.FrameState = 2
